# Generated by Django 4.1 on 2023-01-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchroom_host', to='api.account')),
                ('messages', models.ManyToManyField(blank=True, related_name='watchroom_messages', to='api.message')),
                ('users', models.ManyToManyField(related_name='watchroom_users', to='api.account')),
            ],
        ),
    ]
